### ISSUE TITLE
HardRock crashes the visualizer sometimes

### ISSUE THREAD

**Issue by melloeOsu** [Syriiin/UniCircleDifficulty#3]
it's only for some maps. it seems like it's for the harder ones? I tried snow note's inbachi and rizia's mafumafu revenge, but I also tried byakuya gensoutan extra diffs and my own Seashore on the moon, all of them crashed the visualizer. maybe it's only my visualizer. even for maps that were not that difficult sometimes it would crash.

**Comment by Syriiin** [comment]
Same root bug as #2

Fixed in ac23a877aa988a580937026c1a66e60a5112ee13
